### ISSUE TITLE
php-fpm Service Not Found on PHP 5 Installations

### ISSUE THREAD

**Issue by jcderose** [sous-chefs/php#158]
I'm running a test kitchen instance with Ubuntu 14.04 and PHP 5.5.9. I can install the php5-fpm package manually, but the `php_fpm_pool` resource notifies/restarts php-fpm, not php5-fpm. 

Here's the tail of the chef-client run output:

```
       Running handlers:
       [2016-01-11T21:25:01+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-01-11T21:25:01+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 25.579421826 seconds
       [2016-01-11T21:25:01+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-01-11T21:25:01+00:00] ERROR: resource template[/etc/php5/fpm/pool.d/wordpress.conf] is configured to notify resource service[php-fpm] with action restart, but service[php-fpm] cannot be found in the resource collection. template[/etc/php5/fpm/pool.d/wordpress.conf] is defined in /tmp/kitchen/cache/cookbooks/php-fpm/definitions/php_fpm_pool.rb:27:in `block in from_file'

       [2016-01-11T21:25:02+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

I tried overriding the `node['php']['fpm_service']` attribute to `php5-fpm` (instead of `php-fpm`) but Chef is not picking up the change. (Probably a separate issue.)

**Comment by ThatGerber** [comment]
Where are you overriding the attribute? What happens when you left chef handle the php-fpm install (it should be run automatically as part of the first install https://github.com/chef-cookbooks/php/blob/master/providers/fpm_pool.rb#L25?

**Comment by Entr04y** [comment]
I'm running into the same thing installing php56.  It is using the package name instead of what is defined as fpm_service:

```
[2016-01-22T21:33:26+00:00] INFO: Processing file[/etc/php-fpm.d/www.conf] action nothing (/var/chef/runs/d08543aa-d211-421f-bf42-2609ff86933b/local-mode-cache/cache/cookbooks/php/providers/fpm_pool.rb line 34)
[2016-01-22T21:33:26+00:00] INFO: Processing yum_package[php56-fpm] action install (/var/chef/runs/d08543aa-d211-421f-bf42-2609ff86933b/local-mode-cache/cache/cookbooks/php/providers/fpm_pool.rb line 37)
[2016-01-22T21:33:26+00:00] INFO: Processing service[php-fpm-5.6] action enable (/var/chef/runs/d08543aa-d211-421f-bf42-2609ff86933b/local-mode-cache/cache/cookbooks/php/providers/fpm_pool.rb line 45)
[2016-01-22T21:33:26+00:00] INFO: Running queued delayed notifications before re-raising exception
[2016-01-22T21:33:26+00:00] ERROR: Running exception handlers
[2016-01-22T21:33:26+00:00] ERROR: Exception handlers complete
[2016-01-22T21:33:26+00:00] FATAL: Stacktrace dumped to /var/chef/runs/d08543aa-d211-421f-bf42-2609ff86933b/local-mode-cache/cache/chef-stacktrace.out
[2016-01-22T21:33:26+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-01-22T21:33:26+00:00] ERROR: resource template[/etc/php-fpm.d/default.conf] is configured to notify resource service[php56-fpm] with action restart, but service[php56-fpm] cannot be found in the resource collection. template[/etc/php-fpm.d/default.conf] is defined in /var/chef/runs/d08543aa-d211-421f-bf42-2609ff86933b/local-mode-cache/cache/cookbooks/php/providers/fpm_pool.rb:56:in `block in class_from_file'
 
[2016-01-22T21:33:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

I've got this set in my attributes default.rb:

```
override['php']['fpm_package']		= 'php56-fpm'
override['php']['fpm_service']		= 'php-fpm-5.6'
```

As you can see it used the correct value when starting the service after install, but is using the package name when notifying after the template.  I've been hunting through the code, but I can't find where it is being overwritten.

**Comment by ThatGerber** [comment]
This seems like a separate issue. There is no php56-fpm package in Ubuntu 14.04. Are you installing from a PPA? Have you correctly added the PPA and run apt-get update prior to running recipe?

**Comment by Entr04y** [comment]
this isn't ubuntu, its AWS linux, using the default package repos.  Everything else is working fine, and if I use the defaults it works, but that is only because the service name happens to be the same as the package name I believe.

**Comment by ThatGerber** [comment]
You're going to want to create a new ticket for the issue since it's unrelated to what's happening in this ticket. AWS Linux is CentOS-based so it's going to be different advice than the advice for Ubuntu 14.04, which is Debian-based.

**Comment by Entr04y** [comment]
Actually, I just found the issue.  Berkshelf is pulling in version 1.7.2 and in providers/fpm_pool.rb the end of the action :install block reads:

```
   notifies :restart, "service[#{node['php']['fpm_package']}]"
  end
  new_resource.updated_by_last_action(t.updated_by_last_action?)
end
```

The current revision shown by github is correct and reads:

```
    notifies :restart, "service[#{node['php']['fpm_service']}]"
  end
  new_resource.updated_by_last_action(t.updated_by_last_action?)
end
```

so the problem is not a platform based problem.  It is the revision that Berkshelf is pulling in by default when specifying:
```
cookbook 'php', '~> 1.7.2'
``` 

as instructed by the supermarket page for the cookbook.

**Comment by lukeowen89** [comment]
Nice spot Entr04y

**Comment by Rockstar04** [comment]
It looks like all that needs to be done is tagging a new patch version, since I am apparently [no longer a maintainer](https://github.com/chef-cookbooks/php/blob/master/MAINTAINERS.md) you guys will need to ping one of those guys about getting a version bump.

**Comment by jcderose** [comment]
Hey @tas50 @sigje @thommay can one of you help out with @Rockstar04 's request above? Or let me know what I need to do to get this issue patched and released?

**Comment by mojowill** [comment]
Any update or workaround for this?

**Comment by jcderose** [comment]
Hey @mojowill , I never got any traction for a patch for this issue from the maintainers (@tas50 @sigje @thommay) but I was able to work-around it by manually declaring the `php5-fpm` service and the necessary php pool config files in my recipe:

```
service 'php5-fpm' do
  action [:enable, :start]
end
template '/etc/php5/fpm/pool.d/wordpress.conf' do
  source 'wordpress_pool.conf.erb'
  owner 'root'
  group 'root'
  mode '0644'
  notifies :restart, 'service[php5-fpm]'
end
template '/etc/php5/fpm/php.ini' do
  source 'fpm-php.ini.erb'
  owner 'root'
  group 'root'
  mode '0644'
  notifies :restart, 'service[php5-fpm]'
end
```

And then adapting these templates to my needs:
https://github.com/chef-cookbooks/php/blob/master/templates/default/fpm-pool.conf.erb
https://github.com/chef-cookbooks/php/blob/master/templates/default/php.ini.erb

**Comment by ThatGerber** [comment]
It might be easier in the interim to just edit the resource after calling the recipe.

```rb
new_resource = resources(service: node['php']['fpm_package'])
new_resource.service_name = node['php']['fpm_service']
```
Then any calls to the package will reference the correct service name instead.

**Comment by iennae** [comment]
Hi folks, I'm @iennae :) I'll take a look at this in a bit. Thanks.

**Comment by Sauraus** [comment]
I am going to bet that if you change that php cookbook version to be higher than what is in supermarket the error will miraculously go away.

**Comment by jcderose** [comment]
Hi @iennae any status update on this one? Or anything we can do to help?

**Comment by Xorima** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
