### ISSUE TITLE
Php_pear package idempotency failure

### ISSUE THREAD

**Issue by dgarstang** [sous-chefs/php#226]
### Cookbook version
4.6.0

### Chef-client version
12.16.42

### Platform Details
CentOS release 6.8 (Final)

### Scenario:
Run chef-client. Maintain php_pear package for Net_GeoIP

### Steps to Reproduce:
Run chef-client

### Expected Result:
chef-client completes successfully.

### Actual Result:
Error is displayed:
```
  * php_pear[Net_GeoIP] action install

    ================================================================================
    Error executing action `install` on resource 'php_pear[Net_GeoIP]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
" | pear -d preferred_state=stable install -a Net_GeoIP ----
    STDOUT: pear/Net_GeoIP is already installed and is the same as the released version 1.0.0
    install failed
    STDERR:
" | pear -d preferred_state=stable install -a Net_GeoIP ----
" | pear -d preferred_state=stable install -a Net_GeoIP returned 1

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/php/libraries/pecl_helpers.rb:74:in `pear_shell_out'
    /var/chef/cache/cookbooks/php/libraries/pecl_helpers.rb:35:in `install_package'
    /var/chef/cache/cookbooks/php/resources/pear.rb:50:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/php/resources/pear.rb:46:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/shipwire_main/recipes/default.rb

    286: php_pear "Net_GeoIP" do
    287:   action :install
    288: end
    289:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/shipwire_main/recipes/default.rb:286:in `from_file'

    php_pear("Net_GeoIP") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :php_pear
      cookbook_name "shipwire_main"
      recipe_name "default"
      binary "pear"
      preferred_state "stable"
      package_name "Net_GeoIP"
    end

    Platform:
    ---------
    x86_64-linux
```

Pinned php cookbook in environment to older version 4.5.0 and error does not occur.

**Comment by damacus** [comment]
So I've confirmed this doesn't work on cents 6 due to it installing a stupidly old version of php, and as a result can't install the package version its been asked to. As noted here 

https://github.com/chef-cookbooks/php/blob/7184e96e1bad0cc160b3babac6541dc0fb333fdb/.travis.yml#L32

Pear does an annoying thing where even if it can't install a version it installs one anyway. Which means if we ask for version 1.1.2 and check for 1.1.2, but pear gives us 1.1.1, we're a bit stuck there.


Try a couple of things 
install a non-eol php
Specify a  version 
Install it manually after installing php. And see what comes back. Including the version number

**Comment by Xorima** [comment]
Hi @dgarstang 

Could you confirm for me if this is still an issue, there have been some major releases since this was raised, so would like to confirm this is still an issue

Thanks !

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
